export const CRITICAL_PACKAGES = new Set([
  'android',
  'android.ext.services',
  'com.android.contacts',
  'com.android.defcontainer',
  'com.android.dialer',
  'com.android.externalstorage',
  'com.android.inputdevices',
  'com.android.inputmethod.latin',
  'com.android.keychain',
  'com.android.launcher',
  'com.android.launcher3',
  'com.android.mms',
  'com.android.packageinstaller',
  'com.android.phone',
  'com.android.providers.downloads',
  'com.android.providers.media',
  'com.android.providers.settings',
  'com.android.providers.telephony',
  'com.android.providers.userdictionary',
  'com.android.proxyhandler',
  'com.android.settings',
  'com.android.shell',
  'com.android.systemui',
  'com.android.vending',
  'com.android.vpndialogs',
  'com.android.webview',
  'com.google.android.ext.shared',
  'com.google.android.gms',
  'com.google.android.gmsquick',
  'com.google.android.gsf',
  'com.google.android.gsf.login',
  'com.location.fused',
]);

const LEVE = [
  'com.android.chrome',
  'com.android.htmlviewer',
  'com.android.bookmarkprovider',
  'com.android.printservice.recommendation',
  'com.android.wallpaperpicker',
  'com.android.wallpaper.livepicker',
  'com.android.wallpapercropper',
  'com.android.traceur',
] as const;

const RECOMENDADO = [
  ...LEVE,
  'com.android.calculator2',
  'com.android.documentsui',
  'com.android.printspooler',
  'com.android.bips',
  'com.android.storagemanager',
  'com.android.companiondevicemanager',
  'com.android.providers.downloads.ui',
  'com.android.providers.blockednumber',
  'com.android.settings.intelligence',
  'com.android.systemui.theme.dark',
  'com.android.backupconfirm',
  'com.android.captiveportallogin',
  'com.android.simappdialog',
  'com.android.carrierconfig',
  'com.android.carrierdefaultapp',
  'com.android.onetimeinitializer',
  'com.google.android.backuptransport',
  'com.google.android.partnersetup',
  'com.google.android.gms.setup',
  'com.google.android.onetimeinitializer',
  'com.google.android.syncadapters.contacts',
] as const;

const MAXIMO = [
  ...RECOMENDADO,
  'com.android.pacprocessor',
  'com.android.certinstaller',
  'com.android.provision',
  'com.android.sharedstoragebackup',
  'com.android.statementservice',
  'com.android.cts.ctsshim',
  'com.android.cts.priv.ctsshim',
  'com.android.internal.display.cutout.emulation.corner',
  'com.android.internal.display.cutout.emulation.double',
  'com.android.internal.display.cutout.emulation.tall',
] as const;

export const APP_LABELS: Record<string, string> = {
  'com.android.chrome': 'Chrome',
  'com.android.htmlviewer': 'Visualizador HTML',
  'com.android.bookmarkprovider': 'Favoritos',
  'com.android.printservice.recommendation': 'Serv. de Impressão recomendado',
  'com.android.wallpaperpicker': 'Papel de Parede',
  'com.android.wallpaper.livepicker': 'Papel de Parede ao Vivo',
  'com.android.wallpapercropper': 'Recorte de Papel de Parede',
  'com.android.traceur': 'Traceur',
  'com.android.calculator2': 'Calculadora',
  'com.android.documentsui': 'Arquivos',
  'com.android.printspooler': 'Impressão',
  'com.android.bips': 'Serviço de Impressão',
  'com.android.storagemanager': 'Gerenciador de Armazenamento',
  'com.android.companiondevicemanager': 'Dispositivos Pareados',
  'com.android.providers.downloads.ui': 'Downloads',
  'com.android.providers.blockednumber': 'Números Bloqueados',
  'com.android.settings.intelligence': 'Busca de Ajustes',
  'com.android.systemui.theme.dark': 'Tema Escuro',
  'com.android.backupconfirm': 'Backup do Sistema',
  'com.android.captiveportallogin': 'Login de Rede',
  'com.android.simappdialog': 'Diálogo de SIM',
  'com.android.carrierconfig': 'Config. da Operadora',
  'com.android.carrierdefaultapp': 'App da Operadora',
  'com.android.onetimeinitializer': 'Inicializador',
  'com.google.android.backuptransport': 'Backup do Google',
  'com.google.android.partnersetup': 'Config. Google Partner',
  'com.google.android.gms.setup': 'Setup do GMS',
  'com.google.android.onetimeinitializer': 'Inicializador Google',
  'com.google.android.syncadapters.contacts': 'Sincronização de Contatos',
  'com.android.pacprocessor': 'PacProcessor',
  'com.android.certinstaller': 'Instalador de Certificados',
  'com.android.provision': 'Provisionamento',
  'com.android.sharedstoragebackup': 'Backup Compartilhado',
  'com.android.statementservice': 'App Links',
  'com.android.cts.ctsshim': 'CTS Shim',
  'com.android.cts.priv.ctsshim': 'CTS Priv. Shim',
  'com.android.internal.display.cutout.emulation.corner': 'Cutout de Canto',
  'com.android.internal.display.cutout.emulation.double': 'Cutout Duplo',
  'com.android.internal.display.cutout.emulation.tall': 'Cutout Alto',
  'com.facebook.katana': 'Facebook',
  'com.facebook.appmanager': 'Facebook App Manager',
  'com.facebook.services': 'Facebook Services',
  'com.facebook.system': 'Facebook System',
  'com.facebook.orca': 'Messenger',
  'com.instagram.android': 'Instagram',
  'com.twitter.android': 'Twitter',
  'com.tiktok.android': 'TikTok',
  'com.snapchat.android': 'Snapchat',
  'com.linkedin.android': 'LinkedIn',
  'com.pinterest': 'Pinterest',
  'com.spotify.music': 'Spotify',
  'com.netflix.mediaclient': 'Netflix',
  'com.microsoft.skydrive': 'OneDrive',
  'com.microsoft.office.outlook': 'Outlook',
  'com.microsoft.teams': 'Teams',
  'com.officemobile': 'Office Mobile',
  'com.amazon.mShop.android.shopping': 'Amazon',
  'com.ebay.mobile': 'eBay',
  'com.paypal.android.p2pmobile': 'PayPal',
  'com.king.candycrushsaga': 'Candy Crush',
  'com.supercell.clashofclans': 'Clash of Clans',
  'com.duolingo': 'Duolingo',
  'com.shazam.android': 'Shazam',
  'com.accuweather.android': 'AccuWeather',
  'com.borderfree': 'Borderfree',
  'com.android.vending': 'Google Play Store',
  'com.android.settings': 'Settings',
  'com.android.systemui': 'System UI',
  'com.android.phone': 'Phone',
  'com.android.contacts': 'Contacts',
  'com.android.mms': 'Messages',
  'com.android.dialer': 'Dialer',
  'com.android.launcher': 'Launcher',
  'com.android.launcher3': 'Launcher',
  'com.google.android.gms': 'Google Play Services',
  'com.google.android.gmsquick': 'Google Play Services',
  'com.android.providers.storage': 'Storage',
  'com.android.server.telecom': 'Telecom',
};

export const PRESETS = {
  leve: {
    name: 'Leve',
    description: 'Extras Google: navegador, papel de parede e impressão',
    packages: LEVE,
  },
  recomendado: {
    name: 'Recomendado',
    description: 'Utilitários do sistema e sincronização do Google',
    packages: RECOMENDADO,
  },
  maximo: {
    name: 'Máximo',
    description: 'Todos os pré-instalados que não são críticos',
    packages: MAXIMO,
  },
} as const;

export type PresetKey = keyof typeof PRESETS;

export const BLOATWARE_PACKAGES = new Set<string>([...LEVE, ...RECOMENDADO, ...MAXIMO]);

export function getAppLabel(packageName: string): string {
  return APP_LABELS[packageName] || packageName.split('.').pop() || packageName;
}
